### PR TITLE
Added subscription icon to Ardour due to payment plan

### PR DESCRIPTION
**Pull request by mon1kasenpai**

### CODE REVIEW

**Comment by KenneyNL** [comment]
Could you link to where it says something about the payment plan?

**Comment by begin-theadventure** [comment]
_On their website https://community.ardour.org/download_
(You have to click `Ready-to-Run Program`->`GNU/Linux` / `Windows` / `macOS`->`Download Ardour`...
Subscribe | Single Payment | Free/Demo Version

**Comment by DeerTears** [comment]
But you can build the program to keep it free, right? Keeping in mind Asesprite is considered free and open source on this list, but they're still asking for money if you want a compiled binary.

**Comment by begin-theadventure** [comment]
I'd tag it as `✨ (💵, 🔒)`.
✨ =  FOSS, and such software can be built for free in most if not all cases, which most probably people won't do anyway, because they will get the binaries elsewhere or just pay.

**Comment by KenneyNL** [comment]
Added the tag as specified by @begin-theadventure

**Pull request closed without merging**
